"""initial

Revision ID: 0ee920f5d7f5
Revises: 
Create Date: 2026-02-04 13:31:08.191864

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0ee920f5d7f5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auctions',
    sa.Column('guid', sa.UUID(), nullable=False),
    sa.Column('number', sa.String(length=100), nullable=True),
    sa.Column('etp_id', sa.String(length=255), nullable=True),
    sa.Column('organizer_inn', sa.String(length=20), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('guid')
    )
    op.create_index(op.f('ix_auctions_number'), 'auctions', ['number'], unique=False)
    op.create_index(op.f('ix_auctions_organizer_inn'), 'auctions', ['organizer_inn'], unique=False)
    op.create_table('system_state',
    sa.Column('task_key', sa.String(length=50), nullable=False),
    sa.Column('last_processed_date', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('task_key')
    )
    op.create_table('lots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('guid', sa.UUID(), nullable=True),
    sa.Column('auction_id', sa.UUID(), nullable=False),
    sa.Column('lot_number', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('start_price', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('category_code', sa.String(length=20), nullable=True),
    sa.Column('cadastral_numbers', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('is_restricted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['auction_id'], ['auctions.guid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('auction_id', 'lot_number', name='lots_auction_id_lot_number_key')
    )
    op.create_index('idx_lots_cadastral_gin', 'lots', ['cadastral_numbers'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_lots_category_code'), 'lots', ['category_code'], unique=False)
    op.create_index(op.f('ix_lots_guid'), 'lots', ['guid'], unique=False)
    op.create_table('messages',
    sa.Column('guid', sa.UUID(), nullable=False),
    sa.Column('auction_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('date_publish', sa.DateTime(timezone=True), nullable=False),
    sa.Column('content_xml', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['auction_id'], ['auctions.guid'], ),
    sa.PrimaryKeyConstraint('guid')
    )
    op.create_index(op.f('ix_messages_date_publish'), 'messages', ['date_publish'], unique=False)
    op.create_table('price_schedules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lot_id', sa.Integer(), nullable=False),
    sa.Column('date_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('date_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('price', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['lot_id'], ['lots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('price_schedules')
    op.drop_index(op.f('ix_messages_date_publish'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_lots_guid'), table_name='lots')
    op.drop_index(op.f('ix_lots_category_code'), table_name='lots')
    op.drop_index('idx_lots_cadastral_gin', table_name='lots', postgresql_using='gin')
    op.drop_table('lots')
    op.drop_table('system_state')
    op.drop_index(op.f('ix_auctions_organizer_inn'), table_name='auctions')
    op.drop_index(op.f('ix_auctions_number'), table_name='auctions')
    op.drop_table('auctions')
    # ### end Alembic commands ###