"""add fedresurs fields to lots

Revision ID: 661f17671023
Revises: 8613b61acc8b
Create Date: 2026-02-21 04:59:52.124430

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '661f17671023'
down_revision = '8613b61acc8b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lots', sa.Column('debtor_name', sa.Text(), nullable=True))
    op.add_column('lots', sa.Column('debtor_inn', sa.String(length=12), nullable=True))
    op.add_column('lots', sa.Column('debtor_ogrn', sa.String(length=15), nullable=True))
    op.add_column('lots', sa.Column('debtor_address', sa.Text(), nullable=True))
    op.add_column('lots', sa.Column('case_num', sa.String(length=50), nullable=True))
    op.add_column('lots', sa.Column('manager_name', sa.Text(), nullable=True))
    op.add_column('lots', sa.Column('trade_type', sa.String(length=100), nullable=True))
    op.add_column('lots', sa.Column('trade_app_start', sa.String(length=50), nullable=True))
    op.add_column('lots', sa.Column('trade_app_end', sa.String(length=50), nullable=True))
    op.add_column('lots', sa.Column('trade_place', sa.Text(), nullable=True))
    op.add_column('lots', sa.Column('step', sa.String(length=50), nullable=True))
    op.add_column('lots', sa.Column('deposit', sa.String(length=50), nullable=True))
    op.add_column('lots', sa.Column('message_id', sa.String(length=100), nullable=True))
    op.add_column('lots', sa.Column('message_num', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lots', 'category_code',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('lots', 'message_num')
    op.drop_column('lots', 'message_id')
    op.drop_column('lots', 'deposit')
    op.drop_column('lots', 'step')
    op.drop_column('lots', 'trade_place')
    op.drop_column('lots', 'trade_app_end')
    op.drop_column('lots', 'trade_app_start')
    op.drop_column('lots', 'trade_type')
    op.drop_column('lots', 'manager_name')
    op.drop_column('lots', 'case_num')
    op.drop_column('lots', 'debtor_address')
    op.drop_column('lots', 'debtor_ogrn')
    op.drop_column('lots', 'debtor_inn')
    op.drop_column('lots', 'debtor_name')
    op.create_table('cadastral_index',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('cadastral_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('cadastral_quarter', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('address', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('layer_name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('pkk_id', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('data_source', sa.VARCHAR(length=50), server_default=sa.text("'huggingface'::character varying"), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='cadastral_index_pkey'),
    sa.UniqueConstraint('cadastral_number', name='cadastral_index_cadastral_number_key')
    )
    op.create_index('idx_cadastral_quarter', 'cadastral_index', ['cadastral_quarter'], unique=False)
    op.create_index('idx_cadastral_number', 'cadastral_index', ['cadastral_number'], unique=False)
    op.create_table('market_benchmarks',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('cadastral_quarter', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('zone', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('median_price_per_sqm', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('mean_price_per_sqm', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('sample_size', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('data_source', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('last_updated', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='market_benchmarks_pkey')
    )
    # ### end Alembic commands ###