"""add etp fields to lots

Revision ID: 7dfc5094ad39
Revises: a2f4c8e91b30
Create Date: 2026-02-21 20:35:19.175926

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7dfc5094ad39'
down_revision = 'a2f4c8e91b30'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('market_benchmarks')
    op.drop_index('idx_cadastral_number', table_name='cadastral_index')
    op.drop_index('idx_cadastral_quarter', table_name='cadastral_index')
    op.drop_table('cadastral_index')
    op.drop_constraint('leads_source_message_id_key', 'leads', type_='unique')
    op.drop_index('ix_leads_source_message_id', table_name='leads')
    op.create_index(op.f('ix_leads_source_message_id'), 'leads', ['source_message_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_leads_source_message_id'), table_name='leads')
    op.create_index('ix_leads_source_message_id', 'leads', ['source_message_id'], unique=False)
    op.create_unique_constraint('leads_source_message_id_key', 'leads', ['source_message_id'])
    op.create_table('cadastral_index',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('cadastral_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('cadastral_quarter', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('address', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('layer_name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('pkk_id', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('data_source', sa.VARCHAR(length=50), server_default=sa.text("'huggingface'::character varying"), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='cadastral_index_pkey'),
    sa.UniqueConstraint('cadastral_number', name='cadastral_index_cadastral_number_key')
    )
    op.create_index('idx_cadastral_quarter', 'cadastral_index', ['cadastral_quarter'], unique=False)
    op.create_index('idx_cadastral_number', 'cadastral_index', ['cadastral_number'], unique=False)
    op.create_table('market_benchmarks',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('cadastral_quarter', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('zone', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('median_price_per_sqm', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('mean_price_per_sqm', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('sample_size', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('data_source', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('last_updated', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='market_benchmarks_pkey')
    )
    # ### end Alembic commands ###