"""add classification and zone fields

Revision ID: sprint1_classification
Revises: 0ee920f5d7f5
Create Date: 2026-02-05 02:40:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'sprint1_classification'
down_revision: Union[str, None] = '0ee920f5d7f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add new columns to lots table
    op.add_column('lots', sa.Column('location_zone', sa.String(length=20), server_default='OUTSIDE', nullable=False))
    op.add_column('lots', sa.Column('is_relevant', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('lots', sa.Column('semantic_tags', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False))
    op.add_column('lots', sa.Column('red_flags', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False))
    op.add_column('lots', sa.Column('rosreestr_area', sa.Numeric(precision=15, scale=2), nullable=True))
    op.add_column('lots', sa.Column('rosreestr_value', sa.Numeric(precision=20, scale=2), nullable=True))
    op.add_column('lots', sa.Column('rosreestr_vri', sa.String(length=500), nullable=True))
    op.add_column('lots', sa.Column('needs_enrichment', sa.Boolean(), server_default='true', nullable=False))

    # Create indexes
    op.create_index('ix_lots_location_zone', 'lots', ['location_zone'], unique=False)
    op.create_index('ix_lots_is_relevant', 'lots', ['is_relevant'], unique=False)
    op.create_index('ix_lots_needs_enrichment', 'lots', ['needs_enrichment'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_lots_needs_enrichment', table_name='lots')
    op.drop_index('ix_lots_is_relevant', table_name='lots')
    op.drop_index('ix_lots_location_zone', table_name='lots')
    op.drop_column('lots', 'needs_enrichment')
    op.drop_column('lots', 'rosreestr_vri')
    op.drop_column('lots', 'rosreestr_value')
    op.drop_column('lots', 'rosreestr_area')
    op.drop_column('lots', 'red_flags')
    op.drop_column('lots', 'semantic_tags')
    op.drop_column('lots', 'is_relevant')
    op.drop_column('lots', 'location_zone')
    # ### end Alembic commands ###
